# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class GriddoEnv < Formula
  desc "Griddo env generator"
  homepage "https://github.com/griddo/env-generator"
  version "1.4.11"
  depends_on :macos

  url "https://github.com/Secuoyas-Experience/env-generator/releases/download/v1.4.11/env-generator_1.4.11_darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
  sha256 "596e109a91b0329e5fb2bc5c1ed6c7822c80017518ba2d2551aafacfdd103c5d"

  def install
    bin.install "griddo-env"
  end
end
