# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class GriddoEnv < Formula
  desc "Griddo env generator"
  homepage "https://github.com/griddo/env-generator"
  version "1.4.12"
  depends_on :macos

  url "https://github.com/Secuoyas-Experience/env-generator/releases/download/v1.4.12/env-generator_1.4.12_darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
  sha256 "44f0ffc78c1dd0991d26d22f76b2691f990cea25c81be1dcba8e05c734fce2b4"

  def install
    bin.install "griddo-env"
  end
end
