# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class GriddoEnv < Formula
  desc "Griddo env generator"
  homepage "https://github.com/griddo/env-generator"
  version "1.4.10"
  depends_on :macos

  url "https://github.com/Secuoyas-Experience/env-generator/releases/download/v1.4.10/env-generator_1.4.10_darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
  sha256 "a27e478c20c79a2336d52cee161966c16b5bbfed3b81577cb7359930129e8df5"

  def install
    bin.install "griddo-env"
  end
end
