# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class GriddoEnv < Formula
  desc "Griddo env generator"
  homepage "https://github.com/griddo/env-generator"
  version "1.2.3"
  depends_on :macos

  on_macos do
    url "https://github.com/Secuoyas-Experience/env-generator/releases/download/v1.2.3/env-generator_1.2.3_darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "56cb57f353411f3e6d7943e07aac694378675ad68098981ff240ea10814d2f40"

    def install
      bin.install "griddo-env"
    end
  end
end
